-- ═══════════════════════════════════════════════════════════════════════════
-- Migratie 004 — Profielen, Documenten & Medewerker-accounts
-- Uitvoeren via: Supabase Dashboard → SQL Editor → Plak dit bestand
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── 1. Uitnodigingsvelden op employees ──────────────────────────────────────
ALTER TABLE planner20_employees
  ADD COLUMN IF NOT EXISTS invite_sent_at  timestamptz,
  ADD COLUMN IF NOT EXISTS invite_pending  boolean DEFAULT false;

-- ─── 2. Uitgebreid profiel per medewerker ────────────────────────────────────
CREATE TABLE IF NOT EXISTS planner20_employee_profiles (
  employee_id        integer PRIMARY KEY
                       REFERENCES planner20_employees(id) ON DELETE CASCADE,
  voornaam           text,
  achternaam         text,
  adres              text,
  postcode           text,
  stad               text,
  ice_contact        text,                         -- ICE: naam + telefoonnummer
  geboortedatum      date,
  geboorteplaats     text,
  land_van_herkomst  text DEFAULT 'Nederland',
  bijzonderheden     text,
  voorkeur_planning  jsonb,                        -- { dagen:{ma:true,...}, tijdvoorkeur:'ochtend', notitie:'' }
  avatar_path        text,                         -- pad in Supabase Storage bucket 'employee-avatars'
  updated_at         timestamptz DEFAULT now()
);

-- ─── 3. Beveiligde documenten ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS planner20_employee_documents (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   integer NOT NULL
                  REFERENCES planner20_employees(id) ON DELETE CASCADE,
  doc_type      text NOT NULL
                  CHECK (doc_type IN ('legitimatie', 'arbeidsovereenkomst', 'overig')),
  filename      text NOT NULL,
  storage_path  text NOT NULL UNIQUE,             -- pad in Supabase Storage bucket 'employee-documents'
  file_size     integer,                          -- bytes
  mime_type     text,
  uploaded_by   text NOT NULL,                    -- user_id van wie het uploadte
  uploaded_at   timestamptz DEFAULT now(),
  notes         text
);

CREATE INDEX IF NOT EXISTS planner20_employee_documents_emp_idx
  ON planner20_employee_documents (employee_id);

-- ─── 4. Seed: 11 medewerkers ─────────────────────────────────────────────────
-- Let op: deze INSERT gebruikt expliciete IDs (101–111).
-- Pas ze aan als die IDs al in gebruik zijn.

INSERT INTO planner20_employees
  (id, name, email, phone, contract_hours, is_active, user_level, team_group, location, hourly_rate)
VALUES
  (101, 'Jens Smits',         'j.smits10@hotmail.com',          null, 16, 1, 'Medewerker', null, 'markt', null),
  (102, 'Jip Lavrijsen',      'lavrijsen.jip@2college.nl',      null, 16, 1, 'Medewerker', null, 'markt', null),
  (103, 'John van Hooft',     'j.frietboer@gmail.com',          null, 16, 1, 'Medewerker', null, 'markt', null),
  (104, 'Suus Roosen',        'suusroosen06@gmail.com',         null, 16, 1, 'Medewerker', null, 'markt', null),
  (105, 'Tess Overbeek',      'toverbeek429@gmail.com',         null, 16, 1, 'Medewerker', null, 'markt', null),
  (106, 'Huub Bruggeling',    'hwa.bruggeling@hotmail.com',     null, 16, 1, 'Medewerker', null, 'markt', null),
  (107, 'Mayke Fransen',      'mayke.fransen@outlook.com',      null, 16, 1, 'Medewerker', null, 'markt', null),
  (108, 'Twan Vermeer',       'twan.vermeer.2011@gmail.com',    null, 16, 1, 'Medewerker', null, 'markt', null),
  (109, 'Giel van Hal',       'gielvanhal4@gmail.com',          null, 16, 1, 'Medewerker', null, 'markt', null),
  (110, 'Troy Blommensteijn', 'troy.blommensteijn@hotmail.com', null, 16, 1, 'Medewerker', null, 'markt', null),
  (111, 'Stijn Wolfs',        'stijnwolfs0608@gmail.com',       null, 16, 1, 'Medewerker', null, 'markt', null)
ON CONFLICT (id) DO NOTHING;

-- Zorg dat de auto-increment sequence boven de ingevoegde IDs staat
DO $$
DECLARE
  seq text;
BEGIN
  SELECT pg_get_serial_sequence('planner20_employees', 'id') INTO seq;
  IF seq IS NOT NULL THEN
    PERFORM setval(seq, GREATEST((SELECT MAX(id) FROM planner20_employees), 200));
  END IF;
END $$;

-- ─── 5. Supabase Storage buckets (voer dit uit of maak ze aan via Dashboard) ──
-- Bucket: employee-avatars  → profiel-foto's  (privé, signed URLs)
-- Bucket: employee-documents → gevoelige documenten (privé, signed URLs)
--
-- Als je Supabase Storage via SQL wilt aanmaken:
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('employee-avatars',   'employee-avatars',   false, 5242880,  ARRAY['image/jpeg','image/png','image/webp']),
  ('employee-documents', 'employee-documents', false, 10485760, ARRAY['application/pdf','image/jpeg','image/png','image/webp'])
ON CONFLICT (id) DO NOTHING;
